dry-run: null
hookfiles: null
sandbox: false
server: go run server.go
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: apiary
output: []
header: []
sorted: true
user: null
inline-errors: false
details: true
method: false
color: true
level: info
timestamp: true
silent: false
path: []
blueprint: 'blueprint.md'
endpoint: 'http://localhost:3000'
