dry-run: null
hookfiles: 'dreddhooks.js'
sandbox: false
server: 'go run server.go'
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: 'cli'
output: []
header: []
sorted: true
user: null
inline-errors: false
details: true
method: ['OPTIONS', 'POST', 'GET', 'DELETE']
color: true
level: 'info'
timestamp: true
silent: false
path: []
blueprint: 'blueprint.md'
endpoint: 'http://localhost:3000'
